=== simonhampe/fsframework/schema/LocalizedStringTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="fsframework" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fsframework="fsframework">
	<xsd:element name="locstringtable" type="fsframework:locstringtable"></xsd:element>   
   
    <xsd:complexType name="localelist">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
    		<xsd:element name="locale" type="fsframework:locale" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="locale">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
    		<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="desc" type="xsd:string" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="stringtable">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
    		<xsd:element name="localstring" type="fsframework:localstring" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="stringtables">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
    		<xsd:element name="table" type="fsframework:stringtable" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>




    <xsd:complexType name="localstring">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:string">
    			<xsd:attribute name="locale" type="xsd:string" use="required"></xsd:attribute>
    		</xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>
    
    <xsd:complexType name="locstringtable">
    	<xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="localelist" type="fsframework:localelist"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
            <xsd:element name="stringtables"
    			type="fsframework:stringtables" maxOccurs="1" minOccurs="1">
    			<xsd:key name="ids">
    				<xsd:selector xpath="table" />
    				<xsd:field xpath="@id" />
    			</xsd:key>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    
</xsd:schema>

=== simonhampe/fsframework/examples/LocalizedStringTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<fsframework:locstringtable xmlns:fsframework="fsframework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="fsframework ../schema/LocalizedStringTable.xsd ">
  <localelist>
    <locale>
      <name>en</name>
      <desc>English</desc>
    </locale>
    <locale>
		<name>fr</name>
    	<desc>Français</desc>
    </locale>
    <locale>
    	<name>de</name>
    	<desc>Deutsch</desc>
    </locale>
  </localelist>
  <stringtables>
    <table id="button1text">
      <localstring locale="en">push me!</localstring>
    </table>
    <table id="windowtitle">
      <localstring locale="en">Window title</localstring>
      <localstring locale="fr">Titre de la fenêtre</localstring>
      <localstring locale="de">Fenstertitel</localstring>
    </table>
  </stringtables>
</fsframework:locstringtable>
