=== simonhampe/fsframework/schema/PolyglotStringTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.fsmathe.uni-kl.de/fsframework" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fsfw="http://www.fsmathe.uni-kl.de/fsframework">
    
    <xsd:element name="polyglotstringtable" type="fsfw:PolyglotStringTable">
    	<xsd:key name="stringid">
			<xsd:selector xpath="polyglotstring"/>
			<xsd:field xpath="@id"/>
    	</xsd:key>
    </xsd:element>
    
    <xsd:complexType name="PolyglotStringTable">
        <xsd:sequence>
        	<xsd:element name="description" type="xsd:string"
        		maxOccurs="1" minOccurs="1">
        	</xsd:element>
        	<xsd:element name="languagetable" type="fsfw:LanguageTable"
        		maxOccurs="1" minOccurs="1">
        		<xsd:key name="languageid">
        			<xsd:selector xpath="language" />
        			<xsd:field xpath="id" />
        		</xsd:key>
        	</xsd:element>
            <xsd:element name="polyglotstring"
        		type="fsfw:PolyglotString" maxOccurs="unbounded"
        		minOccurs="0">
        		<xsd:key name="variantid">
        			<xsd:selector xpath="variant" />
        			<xsd:field xpath="@lang" />
        		</xsd:key>
        	</xsd:element>
        </xsd:sequence>
        
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="LanguageTable">
    	<xsd:sequence>
    		<xsd:element name="language" type="fsfw:Language" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Language">
    	<xsd:sequence>
    		<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="PolyglotString">
    	<xsd:sequence>
    		<xsd:element name="variant" type="fsfw:Variant"
    			maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="group" type="xsd:string" use="optional">
    		<xsd:annotation>
    			<xsd:documentation>Defines a hierarchical group relation between different polyglotstrings. This mechanism is used for example by POLYGLOT, the fsframework string table editor to group strings in a more intuitive way. The hierarchy is defined in a way equivalent 
to package naming. This attribute is never actually used in the class PolyglotStringTable itself. If this attribute is empty/whitespace/non-existent, the polyglotstring is in the 'default' group.</xsd:documentation>
    		</xsd:annotation></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Variant">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:string">
    			<xsd:attribute name="lang" type="xsd:string"
    				use="required">
    			</xsd:attribute>
    		</xsd:extension>
    	</xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== simonhampe/fsframework/examples/PolyglotStringTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<fsfw:polyglotstringtable xmlns:fsfw="http://www.fsmathe.uni-kl.de/fsframework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fsmathe.uni-kl.de/fsframework ../schema/PolyglotStringTable.xsd " id="FSFW_PST_EXAMPLE">
  <description>An example polyglot string table for fsframework</description>
  <languagetable>
    <language>
      <id>de</id>
      <description>Deutsch</description>
    </language>
    <language>
    	<id>en</id>
    	<description>English</description>
    </language>
    <language>
    	<id>wu</id>
    	<description>Wuselsch</description>
    </language>
  </languagetable>
  <!-- This table will yield the group hierarchy (root) -> (fs) -> (fs.example)  / (fs.moreexamples)-->
  <polyglotstring id="EX01" group="fs.example">
  	<variant lang="de">Erstes %.4f Beispiel: %s</variant>
  	<variant lang="en">First example</variant>
  </polyglotstring>
  <polyglotstring id="EX02" group="fs.moreexamples">
  	<variant lang="wu">Wusel</variant>
  	<variant lang="xy">This is an example for a language which is actually used, but not listed in the language table</variant>
  </polyglotstring>
</fsfw:polyglotstringtable>
